# Generated by Django 5.0.6 on 2024-07-30 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoExtensao',
            fields=[
                ('idAcao', models.AutoField(primary_key=True, serialize=False)),
                ('TituloAcao', models.CharField(max_length=255)),
                ('coordenadorAcao', models.CharField(max_length=255)),
                ('alunoAcao', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoAcao',
            fields=[
                ('idSituacao', models.AutoField(primary_key=True, serialize=False)),
                ('nomeSituacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAcao',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('nomeTipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EdicaoAcao',
            fields=[
                ('idEdicao', models.AutoField(primary_key=True, serialize=False)),
                ('numEdicao', models.SmallIntegerField()),
                ('nomeEdicao', models.CharField(max_length=255)),
                ('idAcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.acaoextensao')),
            ],
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='idSituacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.situacaoacao'),
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='idTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.tipoacao'),
        ),
    ]
