# Generated by Django 5.0.6 on 2024-08-07 17:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('idCidade', models.AutoField(primary_key=True, serialize=False)),
                ('Cidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('UF', models.CharField(max_length=255)),
                ('Estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='acaoextensao',
            old_name='localizacao',
            new_name='Bairro',
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='CEP',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='Complemento',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='Numero',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='Rua',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='descricao',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='dtCriacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='dtFim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='dtInicio',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='dtModificacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='Cidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.cidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cidades',
            name='UF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.estados'),
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='UF',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.estados'),
            preserve_default=False,
        ),
    ]
