# Generated by Django 5.0.6 on 2024-08-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0002_cidades_estados_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
