# Generated by Django 5.0.6 on 2024-08-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0002_acaoextensao_dtcriacao_acaoextensao_dtfim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoextensao',
            name='Descricao',
            field=models.CharField(default='Default description', max_length=500),
            preserve_default=False,
        ),
    ]
