# Generated by Django 5.0.6 on 2024-08-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0003_acaoextensao_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acaoextensao',
            old_name='Descricao',
            new_name='descricao',
        ),
    ]
