# Generated by Django 5.0.6 on 2024-08-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0003_delete_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acaoextensao',
            old_name='Cidade',
            new_name='idCidade',
        ),
        migrations.RenameField(
            model_name='acaoextensao',
            old_name='UF',
            new_name='idEstado',
        ),
    ]
