# Generated by Django 5.0.6 on 2024-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0004_rename_cidade_acaoextensao_idcidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoAcao',
            fields=[
                ('idContato', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
