# Generated by Django 5.0.6 on 2024-08-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0005_contatoacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='contatoimages/'),
        ),
    ]
