# Generated by Django 5.0.6 on 2024-08-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0007_acaoextensao_imagem_alter_contatoacao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaoextensao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projectsimages/'),
        ),
        migrations.AlterField(
            model_name='contatoacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='contactsimages/'),
        ),
    ]
