# Generated by Django 5.0.6 on 2024-08-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0008_alter_acaoextensao_imagem_alter_contatoacao_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('acao_extensao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='GTMaisapp.acaoextensao')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('Contato_Acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='GTMaisapp.contatoacao')),
            ],
        ),
    ]
