# Generated by Django 5.0.6 on 2024-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0009_imagemacao_imagemcontato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaoextensao',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='contatoacao',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='imagemacao',
            name='imagem',
            field=models.ImageField(upload_to='projectsimages/'),
        ),
        migrations.AlterField(
            model_name='imagemcontato',
            name='imagem',
            field=models.ImageField(upload_to='contactsimages/'),
        ),
    ]
