# Generated by Django 5.0.6 on 2024-08-13 17:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0011_acaoextensao_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('codAreaConhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('idPessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.IntegerField(max_length=255)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='Bairro',
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='Complemento',
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='Rua',
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='dtFim',
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='dtInicio',
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='dtModificacao',
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='idCidade',
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='idEstado',
        ),
        migrations.RemoveField(
            model_name='acaoextensao',
            name='idSituacao',
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='CEP',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='Complemento',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='aceitaContribuicoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='artigo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='bairro',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='contato',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='dtFim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='dtInicio',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='dtModificacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='idCidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.cidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='idEstado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.estados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='idSituacao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.situacaoacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='numero',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='rua',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('idPessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('permissao', models.CharField(max_length=255)),
                ('idPessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.pessoa')),
            ],
        ),
    ]
