# Generated by Django 5.0.6 on 2024-08-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0012_areaconhecimento_pessoa_remove_acaoextensao_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
