# Generated by Django 5.0.6 on 2024-08-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0014_alter_pessoa_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('idEndereco', models.AutoField(primary_key=True, serialize=False)),
                ('CEP', models.CharField(max_length=255)),
                ('numero', models.SmallIntegerField()),
                ('complemento', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='edicaoacao',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='edicaoacao',
            name='Complemento',
        ),
        migrations.RemoveField(
            model_name='edicaoacao',
            name='aceitaContribuicoes',
        ),
        migrations.RemoveField(
            model_name='edicaoacao',
            name='artigo',
        ),
        migrations.RemoveField(
            model_name='edicaoacao',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='edicaoacao',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='edicaoacao',
            name='idSituacao',
        ),
        migrations.RemoveField(
            model_name='edicaoacao',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='edicaoacao',
            name='rua',
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='aceitaContribuicoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='artigo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='contato',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='idSituacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.situacaoacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='idEndereco',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicaoacao',
            name='idEndereco',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.endereco'),
            preserve_default=False,
        ),
    ]
