# Generated by Django 5.0.6 on 2024-08-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0015_endereco_remove_edicaoacao_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoextensao',
            name='idCidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.cidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoextensao',
            name='idEstado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GTMaisapp.estados'),
            preserve_default=False,
        ),
    ]
