# Generated by Django 5.0.6 on 2024-08-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTMaisapp', '0017_edicaoacao_alunoacao_edicaoacao_contato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edicaoacao',
            old_name='alunoAcao',
            new_name='alunoEdicao',
        ),
        migrations.RenameField(
            model_name='edicaoacao',
            old_name='coordenadorAcao',
            new_name='coordenadorEdicao',
        ),
    ]
